### ISSUE TITLE
Add support for higher resolution textures

### ISSUE THREAD

**Issue by fo-od** [SkyblockerMod/Skyblocker#108] opened 2023-01-07 23:11 UTC
so basically add support for whenever people use texturepacks to replace the textures for this mod, they can use higher res, i tried doing this and this is what happened:
texture file: (768x768)
![image](https://user-images.githubusercontent.com/99752044/211173250-12837cf0-bca4-4249-9d8c-60d652be2f90.png)
ingame:
![image](https://user-images.githubusercontent.com/99752044/211173580-bf900ff0-ab45-4f25-94b5-8e5d00d7eedf.png)

**Comment by fo-od** [comment] 2023-01-08 02:42
i found a hacky solution!! (only for gui scale 3)
use this as a template
![bars](https://user-images.githubusercontent.com/99752044/211178155-03042986-9740-4872-8276-d6afdbf9e4ef.png)

**Comment by Julienraptor01** [comment] 2023-01-08 17:34
> i found a hacky solution!! (only for gui scale 3)
> use this as a template
> ![bars](https://user-images.githubusercontent.com/99752044/211178155-03042986-9740-4872-8276-d6afdbf9e4ef.png)
> 

I would say don't close the issue as it's still not really supported and you just found a hacky way.
Just so that the issue is still tracked to maybe fix the issue properly

**Comment by fo-od** [comment] 2023-01-08 18:47
> 

i mean its not that hacky now that i think about it, but ill reopen this

**Comment by Julienraptor01** [comment] 2023-01-08 18:53
> > 
> 
> i mean its not that hacky now that i think about it, but ill reopen this

Well you had to compress the textures in only 1 axis from what i understood ?

**Comment by fo-od** [comment] 2023-01-08 19:16
> Well you had to compress the textures in only 1 axis from what i understood ?
yes, but now that i think about it more, it looks weird ingame.
health bar for example:
![image](https://user-images.githubusercontent.com/99752044/211214522-f7b520a7-6441-4e96-b2c5-3fe89a6ac0d1.png)
^(how it should look like)
and how it looks ingame:
![image](https://user-images.githubusercontent.com/99752044/211214582-4c7ead11-31cd-4632-83b0-7274b8d967bb.png)
its missing some detail.

**Comment by fo-od** [comment] 2023-01-08 19:22
but when i change the texture to make it taller (changing it vertically) it looks weird.
texture:
![image](https://user-images.githubusercontent.com/99752044/211214737-233b3a62-7e7c-4753-8332-a5731425d00a.png)
ingame:
![image](https://user-images.githubusercontent.com/99752044/211214782-8020cd4c-2be7-400c-9e35-a0c8ab41b8af.png)

**Closed** 2024-04-21 20:10 UTC
Labels: new feature
