### ISSUE TITLE
Crashed on 1.19.2 start-up.

### ISSUE THREAD

**Issue by Apricityx** [SkyblockerMod/Skyblocker#105] opened 2022-12-09 02:07 UTC
When I launch Minecraft,it crashed without game window appearing.Only fabric-API loaded.
MOD version:1.8.2
[crash-2022-12-09_09.56.08-client.txt](https://github.com/SkyblockerMod/Skyblocker/files/10191176/crash-2022-12-09_09.56.08-client.txt)

**Comment by KonaeAkira** [comment] 2022-12-09 14:57
Is this your first time using this mod? Or has it worked for you before and just now stopped working? How long has it been since you last played?

From the log it looks like it crashed while importing all the item data. Go into your config folder and delete the item data folder `config/skyblocker/item-repo`. Then the mod will re-download all the item data on your next startup and hopefully it will work then.

**Comment by Apricityx** [comment] 2022-12-10 04:42
Still crashed.config/skyblocker is a empty floder.

**Comment by seiuna** [comment] 2023-05-30 22:07
since skyblockermod references neu library  I think this is because Chinese Mainland cannot effectively access github
Caused by: org.eclipse.jgit.errors.TransportException: https://github.com/KonaeAkira/NotEnoughUpdates-REPO.git: connection failed

**Comment by AzureAaron** [comment] 2023-05-30 22:16
> since skyblockermod references neu library I think this is because Chinese Mainland cannot effectively access github
> Caused by: org.eclipse.jgit.errors.TransportException: https://github.com/KonaeAkira/NotEnoughUpdates-REPO.git: connection failed

This is indeed the case, I had a friend in Mainland China that couldn't download the repo without a VPN.

**Comment by Julienraptor01** [comment] 2023-06-08 11:41
maybe we could have some GH alternative which automatically sync the NEU repo and make it accessible, kinda like a redistribution proxy

**Comment by kevinthegreat1** [comment] 2023-06-25 09:43
I believe this is fixed in the newest versions. The game no longer crashes.

**Closed by kevinthegreat1** 2023-06-25 09:43 UTC
Labels: bug
