### ISSUE TITLE
Fancy tab bugs

### ISSUE THREAD

**Issue by Kolobok125040** [SkyblockerMod/Skyblocker#353] opened 2023-10-10 14:27 UTC
### What happened?

In fancy tab I can't see my Farming level if it's maxed out. (my lvl - 51 with cap)

Also crop milestones for warts, cocoa and cane are not displayed.

### Screenshots

![изображение](https://github.com/SkyblockerMod/Skyblocker/assets/60614259/3958eadd-34ef-40e6-aef9-0ccc72ffd7cb)

### Minecraft Version

1.201

### Skyblocker Version

skyblocker-1.14.0+1.20.1.jar

**Comment by msg-programs** [comment] 2023-10-10 17:38
Could you send a screenshot of what the "normal" tab hud displays?

**Comment by LifeIsAParadox** [comment] 2023-10-10 19:41
for me the crop part works but for the level part
![2023-10-10_21 38 53](https://github.com/SkyblockerMod/Skyblocker/assets/19829407/a385329c-7a47-4cc8-8560-b3584147c0e3)

**Comment by Kolobok125040** [comment] 2023-10-12 08:06
Here, if you still need it
![изображение](https://github.com/SkyblockerMod/Skyblocker/assets/60614259/a5dd4d3f-fd13-494f-970e-63fdef05f232)

**Comment by msg-programs** [comment] 2023-10-12 20:24
It's caused by the maxed skill not containing a % and by "Nether Wart" containing a space.
I'll put the (untested) fix here until I can make a build for testing. Switching between branches is a bit difficult until #355 is merged due to the package renaming commit making it super sketchy, so this has to wait until the PR gets though. Sorry :(

```JAVA
    private static final Pattern SKILL_PATTERN = Pattern
            .compile("\\S*: (?<skill>[A-Za-z]* [0-9]*): (?<progress>[0-9.]+|MAX)");

    private static final Pattern MS_PATTERN = Pattern.compile("\\S*: (?<milestone>[A-Za-z ]* [0-9]*): (?<progress>\\S*)%");

    @Override
    public void updateContent() {
    // ...

            if (strpcnt.equals("MAX")) {
                pc = new ProgressComponent(Ico.LANTERN, Text.of(skill), Text.of("MAX"), 100f, Formatting.RED.getColorValue());
            } else {
                float pcnt = Float.parseFloat(strpcnt);
                pc = new ProgressComponent(Ico.LANTERN, Text.of(skill), pcnt,
                Formatting.GOLD.getColorValue());
            }
        }
    // ...
    }
```

**Comment by msg-programs** [comment] 2023-10-22 09:42
Try this build. No idea why cacti would break anything, but it should at least fix the nether warts and the maxed skill.

[skyblocker-1.14.0+1.20.2.jar.zip](https://github.com/SkyblockerMod/Skyblocker/files/13062852/skyblocker-1.14.0%2B1.20.2.jar.zip)

**Closed** 2023-10-30 04:23 UTC
Labels: bug
