### ISSUE TITLE
Mixin injection failed on launch

### ISSUE THREAD

**Issue by minhperry** [SkyblockerMod/Skyblocker#551] opened 2024-02-18 13:36 UTC
### What happened?

On mixin injection stage the mod **might** have conflict with Debugify 1.20.4+1.0 as in the log below
Disabling Skyblocker makes the game runs fine. Log is Prism Launcher log.

### Log output

https://mclo.gs/buPSf8g

### Minecraft Version

1.20.4

### Skyblocker Version

1.17.0-1.20.4

**Comment by minhperry** [comment] 2024-02-18 13:39
Another relaunch with other disabled mods https://mclo.gs/jAAWyBG

**Comment by viciscat** [comment] 2024-02-18 14:04
Hello!
Looking at your mods it's actually a conflict with kennytvs-epic-force-close-loading-screen-mod-for-fabric. It's because both skyblocker and that mod try to do the same thing. The only difference is that skyblocker's one is only enabled during skyblock.
So for now just remove kennytvs-epic-force-close-loading-screen-mod-for-fabric.
I will try and cook up a quick fix at some point.

**Comment by x-yingcan-x** [comment] 2024-02-18 15:16
see #478 
fixed on kennytv's side, but u need to download the build, the released one(2.2.0) doesnt including this fix

**Comment by AzureAaron** [comment] 2024-03-07 20:55
Duplicate of #478

**Closed by AzureAaron** 2024-03-07 20:55 UTC
Labels: invalid, compatibility, crash
