### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by NhunorGaming** [SkyblockerMod/Skyblocker#75] opened 2022-06-17 19:10 UTC
When I leave a server the game crashes

---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 2022. 06. 17. 20:44
Description: Unexpected error

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_634.method_2880()" because the return value of "net.minecraft.class_310.method_1562()" is null
	at Not Enough Crashes deobfuscated stack trace.(1.18.1+build.22)
	at me.xmrvizzy.skyblocker.skyblock.BackpackPreview.getSkyblockProfile(BackpackPreview.java:171)
	at me.xmrvizzy.skyblocker.skyblock.BackpackPreview.tick(BackpackPreview.java:49)
	at me.xmrvizzy.skyblocker.utils.Scheduler$CyclicTask.run(Scheduler.java:53)
	at me.xmrvizzy.skyblocker.utils.Scheduler$ScheduledTask.run(Scheduler.java:65)
	at me.xmrvizzy.skyblocker.utils.Scheduler.tick(Scheduler.java:37)
	at me.xmrvizzy.skyblocker.SkyblockerMod.onTick(SkyblockerMod.java:32)
	at net.minecraft.client.MinecraftClient.handler$bjo000$tick(MinecraftClient:11874)
	at net.minecraft.client.MinecraftClient.tick(MinecraftClient)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1101)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:734)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:37)
	at net.minecraft.client.MinecraftClient.modify$bil000$atTheEndOfSecondCatchBeforePrintingCrashReport(MinecraftClient:10439)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:761)
	at net.minecraft.client.main.Main.main(Main:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at me.xmrvizzy.skyblocker.skyblock.BackpackPreview.getSkyblockProfile(BackpackPreview.java:171)
	at me.xmrvizzy.skyblocker.skyblock.BackpackPreview.tick(BackpackPreview.java:49)
	at me.xmrvizzy.skyblocker.utils.Scheduler$CyclicTask.run(Scheduler.java:53)
	at me.xmrvizzy.skyblocker.utils.Scheduler$ScheduledTask.run(Scheduler.java:65)
	at me.xmrvizzy.skyblocker.utils.Scheduler.tick(Scheduler.java:37)
	at me.xmrvizzy.skyblocker.SkyblockerMod.onTick(SkyblockerMod.java:32)
	at net.minecraft.class_310.handler$bjo000$tick(class_310.java:11874)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods, Essential (fabric_1.19).jar
Stacktrace:
	at net.minecraft.class_6360.method_36565(class_6360.java:49)
	at net.minecraft.class_310.method_1587(class_310.java:2295)
	at net.minecraft.class_310.method_1514(class_310.java:758)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:37)
	at net.minecraft.class_310.modify$bil000$atTheEndOfSecondCatchBeforePrintingCrashReport(class_310.java:10439)
	at net.minecraft.class_310.method_1514(class_310.java:761)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 1.19
	Minecraft Version ID: 1.19
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 311092488 bytes (296 MiB) / 1644167168 bytes (1568 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 8
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx  
	Identifier: AuthenticAMD Family 23 Model 24 Stepping 1
	Microarchitecture: unknown
	Frequency (GHz): 2,10
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: AMD Radeon(TM) Vega 8 Graphics
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 2048,00
	Graphics card #0 deviceId: 0x15d8
	Graphics card #0 versionInfo: DriverVersion=30.0.13044.10001
	Memory slot #0 capacity (MB): 4096,00
	Memory slot #0 clockSpeed (GHz): 2,40
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384,00
	Memory slot #1 clockSpeed (GHz): 2,93
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 36810,96
	Virtual memory used (MB): 23017,74
	Swap memory total (MB): 18432,00
	Swap memory used (MB): 645,12
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		appleskin: AppleSkin 2.4.0+mc1.19
		bobby: Bobby 4.0.0
			com_typesafe_config: config 1.4.2
			fabric-api-base: Fabric API Base 0.4.9+e62f51a3a9
			fabric-command-api-v2: Fabric Command API (v2) 2.1.1+cda9839ba9
			io_leangen_geantyref_geantyref: geantyref 1.3.13
			org_spongepowered_configurate-core: configurate-core 4.1.2
			org_spongepowered_configurate-hocon: configurate-hocon 4.1.2
		boostedbrightness: Boosted Brightness 2.1.2
		capes: Capes 1.4+1.19
			omega-config: OmegaConfig 1.2.3-1.18.1
		cloth-config: Cloth Config v6 7.0.69
			cloth-basic-math: cloth-basic-math 0.6.1
		completeconfig: CompleteConfig 2.0.0
			coat: Coat 1.0.0-beta.17+mc22w17a
			completeconfig-base: completeconfig-base 2.0.0
			completeconfig-gui-cloth: completeconfig-gui-cloth 2.0.0
			completeconfig-gui-coat: completeconfig-gui-coat 2.0.0
		dynamicfps: Dynamic FPS 2.1.0
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		entityculling: EntityCulling-Fabric 1.5.2-mc1.19
			com_logisticscraft_occlusionculling: occlusionculling 0.0.6-SNAPSHOT
		essential: Essential 3160+feature-fabric-1.19
		essential-container: essential-container 1.0.0
			essential-loader: essential-loader 1.0.0
		fabric: Fabric API 0.55.1+1.19
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.5+9ff28f4057
			fabric-biome-api-v1: Fabric Biome API (v1) 9.0.11+e62f51a357
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.17+9ff28f4057
			fabric-command-api-v1: Fabric Command API (v1) 1.2.3+f71b366f57
			fabric-commands-v0: Fabric Commands (v0) 0.2.20+df3654b357
			fabric-containers-v0: Fabric Containers (v0) 0.1.26+df3654b357
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.0.15+9ff28f4057
			fabric-convention-tags-v1: Fabric Convention Tags 1.0.7+37622d2457
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.2+bd0a0d4a57
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.0.0+2a5b921057
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.26+72da3b3d57
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.15+9ff28f4057
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.25+9ff28f4057
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.23+df3654b357
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.18+1899036157
			fabric-item-api-v1: Fabric Item API (v1) 1.5.3+767db26e57
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.22+9ff28f4057
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.17+9ff28f4057
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.15+df3654b357
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.0.8+21a5acaa57
			fabric-loot-api-v2: Fabric Loot API (v2) 1.0.0+9e7660c657
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.0+9e7660c657
			fabric-message-api-v1: Fabric Message API (v1) 1.0.0+513f4a5957
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.6+9ff28f4057
			fabric-models-v0: Fabric Models (v0) 0.3.14+9ff28f4057
			fabric-networking-api-v1: Fabric Networking API (v1) 1.0.26+7fe9740957
			fabric-networking-v0: Fabric Networking (v0) 0.3.13+df3654b357
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.0.4+9ff28f4057
			fabric-particles-v1: Fabric Particles (v1) 1.0.7+9ff28f4057
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.15+92cf9a3e57
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.0.7+9ff28f4057
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.5+9ff28f4057
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.17+df3654b357
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.11+9ff28f4057
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.4+9ff28f4057
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.19+df3654b357
			fabric-rendering-v1: Fabric Rendering (v1) 1.10.13+9ff28f4057
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.8+e62f51a357
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.5.2+9e7660c657
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.22+9ff28f4057
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.5+9ff28f4057
			fabric-textures-v0: Fabric Textures (v0) 1.0.17+9ff28f4057
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.0.7+e62f51a357
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.1.0+9e7660c657
		fabric-language-kotlin: Fabric Language Kotlin 1.7.4+kotlin.1.6.21
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.6.21
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.6.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.6.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.6.21
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.1
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.1
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.2
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.2
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.2
		fabricloader: Fabric Loader 0.14.8
		ias: In-Game Account Switcher 7.2.0
		java: OpenJDK 64-Bit Server VM 17
		krypton: Krypton 0.2.0
			com_velocitypowered_velocity-native: velocity-native 3.1.2-SNAPSHOT
		lithium: Lithium 0.8.0
		logical_zoom: Logical Zoom 0.0.15
		minecraft: Minecraft 1.19
		modmenu: Mod Menu 4.0.0
		multiconnect: MultiConnect 1.6-beta.12
			multiconnect-api: MultiConnect API 1.6-beta.12
		notenoughcrashes: Not Enough Crashes 4.1.6+1.19
		phosphor: Phosphor 0.8.1
		skyblocker: Skyblocker 1.8.0+1.19.x
			com_github_marcono1234_gson-record-type-adapter-factory: gson-record-type-adapter-factory 0.2.0
			meteordevelopment_discord-ipc: discord-ipc 1.1
			org_eclipse_jgit_org_eclipse_jgit: org.eclipse.jgit 6.0.0.202111291000-r
		sodium: Sodium 0.4.2+build.16
			org_joml_joml: joml 1.10.4
		uglyscoreboardfix: Ugly Scoreboard Fix 2.6.0
	Launched Version: fabric-loader-0.14.8-1.19
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: AMD Radeon(TM) Vega 8 Graphics GL version 3.2.14761 Core Profile Forward-Compatible Context 21.30.44.10 30.0.13044.10001, ATI Technologies Inc.
	Window size: 958x1000
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, Fabric Mods
	Current Language: English (US)
	CPU: 8x AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx 
	Client Crashes Since Restart: 2
	Integrated Server Crashes Since Restart: 0
	Suspected Mods: Skyblocker (skyblocker), Minecraft (minecraft), Fabric Loader (fabricloader), Not Enough Crashes (notenoughcrashes)

**Comment by KonaeAkira** [comment] 2022-06-17 19:19
Closing because it is a duplicate of #73 which has been fixed with in commit [7a8ad1e](https://github.com/SkyblockerMod/Skyblocker/commit/7a8ad1e4f6a7cc3e685a5199a5dd0ca0049c61ff)

**Closed by KonaeAkira** 2022-06-17 19:19 UTC

**Comment by KonaeAkira** [comment] 2022-06-17 19:21
You can use [this beta build](https://github.com/SkyblockerMod/Skyblocker/actions/runs/2515071264) until there is a new official release of the mod ;)

**Comment by NhunorGaming** [comment] 2022-06-17 19:24
Thank you
