### ISSUE TITLE
The TabHUD is not displayed correctly

### ISSUE THREAD

**Issue by R2kip** [SkyblockerMod/Skyblocker#605] opened 2024-03-18 21:02 UTC
### What happened?

The TabHUD is not displayed correctly

### Screenshots

![image](https://github.com/SkyblockerMod/Skyblocker/assets/56793105/8547456d-4406-47c4-891f-4771b3ae714b)
![image](https://github.com/SkyblockerMod/Skyblocker/assets/56793105/d25b90ff-4714-4836-a67c-b59f5aa50867)

### Minecraft Version

1.20.4

### Skyblocker Version

skyblocker-1.18.1-beta-42004f6+1.20.4

**Comment by Julienraptor01** [comment] 2024-03-18 23:17
Yes we know, it's due to the new tab update

**Comment by AzureAaron** [comment] 2024-03-19 16:54
Duplicate of #598

**Closed by AzureAaron** 2024-03-19 16:54 UTC
Labels: bug
