### ISSUE TITLE
Experiments Overlays don't work on Quilt

### ISSUE THREAD

**Issue by a-person1908** [SkyblockerMod/Skyblocker#228] opened 2023-08-04 18:27 UTC
It would be very useful to have for example Experiments Solvers for 1.19.4 but we're stuck to older versions

**Comment by Julienraptor01** [comment] 2023-08-04 18:39
deving for multiple versions create a lot more work, so unless someone want to backport it won't be done but for older versions the experiments solvers were in this mod https://modrinth.com/mod/skyblockmod

**Comment by a-person1908** [comment] 2023-08-04 19:40
hm, I was using that mod mostly for experiments but there wasn't an overlay for experiments at all

**Comment by Julienraptor01** [comment] 2023-08-04 19:46
> hm, I was using that mod mostly for experiments but there wasn't an overlay for experiments at all

unless it's disabled there is an experiment solver in it and it look like this
![image](https://github.com/SkyblockerMod/Skyblocker/assets/49841713/055b99cb-4fd4-40d6-bc2d-c5331663ed46)
![image](https://github.com/SkyblockerMod/Skyblocker/assets/49841713/76974ab9-7262-4e40-b45f-e56540c529f1)

**Comment by a-person1908** [comment] 2023-08-04 19:47
for some reason that didn't even happen for me, I made sure experiments were on

**Comment by a-person1908** [comment] 2023-08-04 20:04
Ohhhhhh

**Comment by a-person1908** [comment] 2023-08-04 20:04
the Overlay function the mod uses doesn't seem to work for quilt

**Comment by a-person1908** [comment] 2023-08-04 20:06
Might be a problem with quilted fabric libraries

**Comment by a-person1908** [comment] 2023-08-04 20:16
Quilt: Only mod difference is quilted api  ![Screenshot 2023-08-04 130056](https://github.com/SkyblockerMod/Skyblocker/assets/137985347/f5f2b0fe-fcec-4526-9ff3-dbd8586b454d)
fabric: Regular  ![Screenshot 2023-08-04 130259](https://github.com/SkyblockerMod/Skyblocker/assets/137985347/cba6d643-968d-49a9-b062-331a90f4ccd1)

Fabric: https://youtu.be/5x1mD9E7_VQ
Quilt: https://youtu.be/cN-RXwZYM0I

**Comment by a-person1908** [comment] 2023-08-04 20:24
Note to that one dev same thing happens with other mods

**Comment by a-person1908** [comment] 2023-08-04 20:26
Yeah its the same between mods 
I belive the mods are attempting to merge

**Comment by Julienraptor01** [comment] 2023-08-04 20:26
Does it also happen with [Skyblocker](https://modrinth.com/mod/skyblocker-liap) on 1.20.1 ?

**Comment by a-person1908** [comment] 2023-08-04 20:27
It happens with 1.19.4 and probably earlier too

**Comment by a-person1908** [comment] 2023-08-04 20:27
it seems to be a rendering issue , maybe a rendering method difference between launchers

**Comment by Julienraptor01** [comment] 2023-08-04 20:35
> *Creating example videos for Skyblocker LIAP*
> 

Don't worry, you don't need to Wohlhabend has confirmed the issue

**Comment by a-person1908** [comment] 2023-08-04 20:36
still gonna do it =p

**Comment by a-person1908** [comment] 2023-08-04 20:39
Quilt: Only mod difference is quilted api (edit: and ig some changes from vanilla quilt)  ![Screenshot 2023-08-04 132925](https://github.com/SkyblockerMod/Skyblocker/assets/137985347/9138ddbe-afbc-487c-9d9a-0d67e5a6bf49)
fabric: Regular  ![Screenshot 2023-08-04 132934](https://github.com/SkyblockerMod/Skyblocker/assets/137985347/663eada5-c342-4341-9064-6321b289a7cf)

Quilt: https://youtu.be/m3kAbl_feQ0
Fabric: https://youtu.be/exe-kMgvBCo

**Comment by Julienraptor01** [comment] 2023-08-04 20:39
This issue should be renamed Experiments Overlays don't work on Quilt

**Comment by LifeIsAParadox** [comment] 2023-08-04 21:05
We primarily support fabric. Unfortunately, we cannot assist with quilt issues.

**Comment by a-person1908** [comment] 2023-08-04 21:13
alr

**Comment by kevinthegreat1** [comment] 2023-08-09 09:13
Afaik quilt should have fabric compatibility, so you can report this to quilt if you want. The only api we use in this part should be Screen Api. Marking this as invalid.

**Comment by kevinthegreat1** [comment] 2023-08-15 15:49
Closing as unable to reproduce on fabric. If you experience similar problems on fabric feel free to reopen.

**Closed by kevinthegreat1** 2023-08-15 15:49 UTC
Labels: invalid
