### ISSUE TITLE
Wiki lookup fails to handle special characters

### ISSUE THREAD

**Issue by Emirlol** [SkyblockerMod/Skyblocker#706] opened 2024-05-13 13:06 UTC
### What happened?

Steps to reproduce:
- Get an `InfiniVacuum™ Hooverius`
- Try to use wiki lookup on it
- The browser opens up `https://wiki.hypixel.net/InfiniVacuum?_Hooverius` rather than `https://wiki.hypixel.net/InfiniVacuum%E2%84%A2_Hooverius`, and that acts as `https://wiki.hypixel.net/InfiniVacuum` with a `GET` request with the `?` at the end and then finally redirects to the incorrect but valid page of `https://wiki.hypixel.net/InfiniVacuum%E2%84%A2` (this last part is just a normal redirection in the wiki).

This probably applies to other items too, but no other item comes to mind.

I'm not sure if this issue is specific to my browser (firefox), how minecraft itself implements opening links or how the data is parsed from the NEU repo. The NEU repo has the correct link with the `™`.

### Minecraft Version

1.20.6

### Skyblocker Version

skyblocker-1.20.2+1.20.4.jar

**Comment by Julienraptor01** [comment] 2024-05-13 14:10
>The browser opens up https://wiki.hypixel.net/InfiniVacuum?_Hooverius rather than https://wiki.hypixel.net/InfiniVacuum%E2%84%A2_Hooverius
this seems like a regression if it's indeed the case as in older versions (1.8.2 + my backport patches) it work as intended and properly open https://wiki.hypixel.net/InfiniVacuum™_Hooverius
could you try the [latest beta](https://modrinth.com/mod/skyblocker-liap/version/1.20.3-beta.2+1.20.6) just in case ?

from a quick look at the code i now see that we are using neu repo parser instead of parsing the json ourselves which could be the actual culprit here
Old code with my backports :
https://github.com/Julienraptor01/Skyblocker/blob/9b1c43f28a62055c4f898c6992e351457ce8e6ad/src/main/java/me/xmrvizzy/skyblocker/skyblock/itemlist/ItemRegistry.java#L121-L136
Current code :
https://github.com/SkyblockerMod/Skyblocker/blob/5eb9d273d2eb56cebaf0be0f90716b362916400b/src/main/java/de/hysky/skyblocker/skyblock/itemlist/ItemRepository.java#L6-L8
https://github.com/SkyblockerMod/Skyblocker/blob/5eb9d273d2eb56cebaf0be0f90716b362916400b/src/main/java/de/hysky/skyblocker/skyblock/itemlist/ItemRepository.java#L67-L83

**Comment by Julienraptor01** [comment] 2024-05-13 15:30
i just tried to replicate the issue on master, but do not get it (i am using firefox too)
maybe it could be due to your os ? i am personally using windows 10 and it work

**Comment by AzureAaron** [comment] 2024-05-13 19:28
Can't reproduce on MacOS 14.4 using Safari 17.4

**Comment by Julienraptor01** [comment] 2024-05-13 19:31
it's actually just a KDE issue with xdg-open and unless we wanna go the sodium route and implement a custom thing to open links, it can be closed

**Comment by AzureAaron** [comment] 2024-05-13 19:32
Perhaps we could work around it by URL encoding opened links, provided the OS doesn't convert them back to their original form?

> it's actually just a KDE issue with xdg-open and unless we wanna go the sodium route and implement a custom thing to open links, it can be closed

**Comment by Julienraptor01** [comment] 2024-05-13 19:37
> Perhaps we could work around it by URL encoding opened links, provided the OS doesn't convert them back to their original form?
> 
> > it's actually just a KDE issue with xdg-open and unless we wanna go the sodium route and implement a custom thing to open links, it can be closed

no, it goes much deeper than that iirc
if you wanna have a proper fix, just look at what jelly did in sodium
https://github.com/CaffeineMC/sodium-fabric/tree/404151901893ad2cfdac91411b86e1e284d904c6/src/desktop/java/net/caffeinemc/mods/sodium/desktop/utils/browse

**Comment by AzureAaron** [comment] 2024-05-14 22:45
Since this is OS-specific bug with minimal impact this will be a won't fix, it's up to KDE in this case to fix their broken implementation which hopefully won't take them long. I don't think many items have these special characters in their name.

When the fix is available I would recommend updating your OS :)

**Closed by AzureAaron** 2024-05-14 22:45 UTC
Labels: bug
