### ISSUE TITLE
crash after joining sky block

### ISSUE THREAD

**Issue by virus00020** [SkyblockerMod/Skyblocker#210] opened 2023-07-26 00:49 UTC
The game crashed whilst unexpected error
Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_332.method_25302(net.minecraft.class_2960, int, int, int, int, int, int)" because "this.hotbarContext" is null is the crash msg after i join sky block server and before i had never got it

**Comment by AzureAaron** [comment] 2023-07-26 01:00
> The game crashed whilst unexpected error
> Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_332.method_25302(net.minecraft.class_2960, int, int, int, int, int, int)" because "this.hotbarContext" is null is the crash msg after i join sky block server and before i had never got it

Which version of the mod are you using?

Can you also provide us with the full crash report/Stack trace?

**Comment by virus00020** [comment] 2023-07-26 02:41
> > The game crashed whilst unexpected error
> > Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_332.method_25302(net.minecraft.class_2960, int, int, int, int, int, int)" because "this.hotbarContext" is null is the crash msg after i join sky block server and before i had never got it
> 
> Which version of the mod are you using?
> 
> Can you also provide us with the full crash report/Stack trace?

the version im using is 1.20 beta

**Comment by virus00020** [comment] 2023-07-26 02:43
> > The game crashed whilst unexpected error
> > Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_332.method_25302(net.minecraft.class_2960, int, int, int, int, int, int)" because "this.hotbarContext" is null is the crash msg after i join sky block server and before i had never got it
> 
> Which version of the mod are you using?
> 
> Can you also provide us with the full crash report/Stack trace?

---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 2023-07-26 01:42:50
Description: Unexpected error

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_332.method_25302(net.minecraft.class_2960, int, int, int, int, int, int)" because "this.hotbarContext" is null
	at net.minecraft.class_329.handler$bee000$skyblocker$renderHotbarItem(class_329.java:3930)
	at net.minecraft.class_329.method_1762(class_329.java)
	at net.minecraft.class_329.handler$bdn000$simple-armor-hud$renderHud(class_329.java:2928)
	at net.minecraft.class_329.method_1753(class_329.java)
	at net.minecraft.class_757.method_3192(class_757.java:926)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_329.handler$bee000$skyblocker$renderHotbarItem(class_329.java:3930)
	at net.minecraft.class_329.method_1762(class_329.java)
	at net.minecraft.class_329.handler$bdn000$simple-armor-hud$renderHud(class_329.java:2928)
	at net.minecraft.class_329.method_1753(class_329.java)

-- Affected level --
Details:
	All players: 14 total; [class_746['virus_h7'/888730, l='ClientLevel', x=-503.00, y=101.00, z=-275.00], class_745['midorimusi1111'/746490, l='ClientLevel', x=-513.50, y=39.00, z=-262.34], class_745['bossdrake'/871960, l='ClientLevel', x=-523.25, y=39.22, z=-298.44], class_745['BoofusB'/802544, l='ClientLevel', x=-520.16, y=39.00, z=-277.50], class_745['Arz081'/419856, l='ClientLevel', x=-573.78, y=9.66, z=-229.34], class_745['SanicYT'/888731, l='ClientLevel', x=-503.00, y=112.00, z=-275.00], class_745['m1cthesp1k'/885773, l='ClientLevel', x=-546.91, y=21.00, z=-307.34], class_745['boomertown38'/839908, l='ClientLevel', x=-553.94, y=59.00, z=-228.72], class_745['Flame024'/863832, l='ClientLevel', x=-581.41, y=55.09, z=-212.78], class_745['LoafyP'/884510, l='ClientLevel', x=-588.69, y=96.47, z=-245.31], class_745['Smarlox'/862521, l='ClientLevel', x=-595.13, y=55.00, z=-201.72], class_745['8wra230806'/72, l='ClientLevel', x=-504.50, y=101.00, z=-284.50], class_745['96ozc1gc3u'/87, l='ClientLevel', x=-524.50, y=101.00, z=-275.50], class_745['043x3490g5'/4, l='ClientLevel', x=-494.50, y=121.00, z=-241.50]]
	Chunk stats: 16384, 225
	Level dimension: minecraft:overworld
	Level spawn location: World: (-503,101,-275), Section: (at 9,5,13 in -32,6,-18; chunk contains blocks -512,0,-288 to -497,255,-273), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 800124723 game time, 507000 day time
	Server brand: Hypixel BungeeCord (1.3.22) <- vanilla
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:458)
	at net.minecraft.class_310.method_1587(class_310.java:2406)
	at net.minecraft.class_310.method_1514(class_310.java:826)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, file/VanillaPlus_V2_1.18.2-1.19.2.zip

-- System Details --
Details:
	Minecraft Version: 1.20
	Minecraft Version ID: 1.20
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 379179096 bytes (361 MiB) / 805306368 bytes (768 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 2
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Celeron(R) CPU  N2840  @ 2.16GHz
	Identifier: Intel64 Family 6 Model 55 Stepping 8
	Microarchitecture: Silvermont
	Frequency (GHz): 2.17
	Number of physical packages: 1
	Number of physical CPUs: 2
	Number of logical CPUs: 2
	Graphics card #0 name: Intel(R) HD Graphics
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 774.68
	Graphics card #0 deviceId: 0x0f31
	Graphics card #0 versionInfo: DriverVersion=10.18.10.5161
	Memory slot #0 capacity (MB): 2048.00
	Memory slot #0 clockSpeed (GHz): 1.33
	Memory slot #0 type: Unknown
	Virtual memory max (MB): 9051.36
	Virtual memory used (MB): 2491.20
	Swap memory total (MB): 7118.00
	Swap memory used (MB): 0.00
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		appleskin: AppleSkin 2.5.0+mc1.20
			cloth-config: Cloth Config v11 11.0.99
				cloth-basic-math: cloth-basic-math 0.6.1
		boostedbrightness: Boosted Brightness 2.1.3
		crystaloptimizer: CrystalOptimizer 1.0.0
		fabric-api: Fabric API 0.86.0+1.20.1
			fabric-api-base: Fabric API Base 0.4.30+7abfd51577
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.35+4d8536c977
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.10+b3afc78b77
			fabric-block-api-v1: Fabric Block API (v1) 1.0.9+e022e5d177
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.40+b3afc78b77
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.1+97bb207577
			fabric-command-api-v1: Fabric Command API (v1) 1.2.33+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.12+b3afc78b77
			fabric-commands-v0: Fabric Commands (v0) 0.2.50+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.62+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.9+b3afc78b77
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.4+a1a980da77
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.18+aeb40ebe77
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.2.0+6c31357e77
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.52+b3afc78b77
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.22+b3afc78b77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.1+e91849a877
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.62+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.38+b04edc7a77
			fabric-item-api-v1: Fabric Item API (v1) 2.1.27+b3afc78b77
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.9+132c48c177
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.36+fb8d95da77
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.34+df3654b377
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.21+b3afc78b77
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.39+b3afc78b77
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.43+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.7+3265161977
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.49+b3afc78b77
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.1+9386d8a777
			fabric-models-v0: Fabric Models (v0) 0.4.0+9386d8a777
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.9+b3afc78b77
			fabric-networking-v0: Fabric Networking (v0) 0.3.49+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.1+6beca84877
			fabric-particles-v1: Fabric Particles (v1) 1.1.1+201a23a077
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.19+b3afc78b77
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.0+2e061fd477
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.1.1+9386d8a777
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.4.1+9172968c77
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.45+df3654b377
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.34+b3afc78b77
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.27+b3afc78b77
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.48+df3654b377
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.7+b3afc78b77
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.5+ea08f9d877
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.9+132c48c177
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.7+b3afc78b77
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.28+b3afc78b77
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.12+b3afc78b77
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.0+cdf060b277
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.0+6c31357e77
		fabricloader: Fabric Loader 0.14.21
		forcecloseworldloadingscreen: kennytv's epic force close loading screen mod for Fabric 2.1.1
		java: OpenJDK 64-Bit Server VM 17
		lithium: Lithium 0.11.2
		minecraft: Minecraft 1.20
		modmenu: Mod Menu 7.0.1
		simple-armor-hud: Simple armor hud 1.20-1.3.0
		skyblocker: Skyblocker 1.10.0-beta-cfae3b8+1.20
			com_github_llamalad7_mixinextras: MixinExtras 0.2.0-beta.9
			com_logisticscraft_occlusionculling: occlusionculling 0.0.7-SNAPSHOT
			meteordevelopment_discord-ipc: discord-ipc 1.1
			org_eclipse_jgit_org_eclipse_jgit: org.eclipse.jgit 6.4.0.202211300538-r
			renderer: Renderer 1.0
				satin: Satin 1.13.0
		sodium: Sodium 0.4.10+build.27
		tooltipscroll: Tooltip Scroll v1.2.5-1.20
	Launched Version: fabric-loader-0.14.21-1.20
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: Intel(R) HD Graphics GL version 3.2.0 - Build 10.18.10.5161, Intel
	Window size: 1366x768
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, fabric, file/VanillaPlus_V2_1.18.2-1.19.2.zip (incompatible)
	Current Language: en_us
	CPU: 2x Intel(R) Celeron(R) CPU N2840 @ 2.16GHz

**Comment by kevinthegreat1** [comment] 2023-07-26 03:55
Seems to be a compatibility issue with `simple-armor-hud`. Caused by a questionable mixin on our end. Fixed in #211.

**Closed** 2023-07-26 04:06 UTC
Labels: bug, compatibility

**Comment by kevinthegreat1** [comment] 2023-07-26 04:08
Thanks for reporting.
